# Generated by Django 5.2 on 2025-05-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='destinations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction', to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='ticketPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
