# Generated by Django 5.2 on 2025-05-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='NumberOfRooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
