# Generated by Django 5.2 on 2025-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_hotel_numberofrooms_hotel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='NumberOfRooms',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
